#!/usr/bin/env bash
# Debian/Ubuntu: install and configure a single VLESS + Reality inbound.
# Run as root. Review PORT and SNI before running in production.
set -Eeuo pipefail
IFS=$'\n\t'
umask 077

PORT=8443
SNI="www.microsoft.com"
CONFIG_PATH="/etc/sing-box/config.json"

die() { printf '[ERROR] %s\n' "$*" >&2; exit 1; }
info() { printf '[INFO] %s\n' "$*"; }

[[ $EUID -eq 0 ]] || die "Run this script as root (for example: sudo bash $0)."
command -v apt-get >/dev/null 2>&1 || die "This script supports Debian/Ubuntu systems with apt-get only."
[[ "$PORT" =~ ^[1-9][0-9]{0,4}$ ]] && (( PORT <= 65535 )) || die "PORT must be 1-65535."
[[ "$SNI" =~ ^[A-Za-z0-9.-]+$ ]] || die "SNI contains unsupported characters."

export DEBIAN_FRONTEND=noninteractive
info "Installing prerequisites..."
apt-get update
apt-get install -y --no-install-recommends ca-certificates curl gpg iproute2 openssl ufw uuid-runtime

# Use the vendor's signed APT repository instead of executing a downloaded installer.
install -d -m 0755 /etc/apt/keyrings
curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
chmod 0644 /etc/apt/keyrings/sagernet.asc
cat >/etc/apt/sources.list.d/sagernet.sources <<'EOF'
Types: deb
URIs: https://deb.sagernet.org/
Suites: *
Components: *
Enabled: yes
Signed-By: /etc/apt/keyrings/sagernet.asc
EOF

apt-get update
apt-get install -y --no-install-recommends sing-box
command -v sing-box >/dev/null 2>&1 || die "sing-box was not installed."

if ss -H -ltn "sport = :$PORT" | grep -q .; then
  die "TCP port $PORT is already in use. Choose another port or stop the conflicting service."
fi

# Reality needs a real TLS target. Fail early if the selected SNI cannot be reached.
info "Checking Reality handshake target: $SNI:443..."
timeout 15 openssl s_client -connect "$SNI:443" -servername "$SNI" </dev/null 2>/dev/null \
  | openssl x509 -noout -subject >/dev/null \
  || die "Cannot obtain a TLS certificate from $SNI:443. Choose a reachable SNI."

UUID=$(cat /proc/sys/kernel/random/uuid)
KEYS=$(sing-box generate reality-keypair)
PRIVATE_KEY=$(awk '/PrivateKey/ {print $2}' <<<"$KEYS")
PUBLIC_KEY=$(awk '/PublicKey/ {print $2}' <<<"$KEYS")
SHORT_ID=$(openssl rand -hex 8)
SERVER_IP=$(curl --fail --silent --show-error --max-time 10 -4 https://api.ipify.org || true)

[[ -n "$PRIVATE_KEY" && -n "$PUBLIC_KEY" ]] || die "Could not parse the Reality key pair generated by sing-box."
[[ -n "$SERVER_IP" ]] || info "Could not determine the public IPv4 address automatically; use this server's public IPv4 in the client."

tmp_config=$(mktemp)
trap 'rm -f "$tmp_config"' EXIT
cat >"$tmp_config" <<EOF
{
  "log": { "level": "info" },
  "inbounds": [
    {
      "type": "vless",
      "tag": "vless-reality-in",
      "listen": "0.0.0.0",
      "listen_port": $PORT,
      "users": [
        { "uuid": "$UUID", "flow": "xtls-rprx-vision" }
      ],
      "tls": {
        "enabled": true,
        "server_name": "$SNI",
        "reality": {
          "enabled": true,
          "handshake": { "server": "$SNI", "server_port": 443 },
          "private_key": "$PRIVATE_KEY",
          "short_id": ["$SHORT_ID"]
        }
      }
    }
  ],
  "outbounds": [ { "type": "direct" } ]
}
EOF

info "Validating generated configuration..."
sing-box check -c "$tmp_config"

install -d -m 0755 /etc/sing-box
if [[ -e "$CONFIG_PATH" ]]; then
  backup_path="${CONFIG_PATH}.backup.$(date +%Y%m%d%H%M%S)"
  cp -p -- "$CONFIG_PATH" "$backup_path"
  info "Existing configuration backed up to $backup_path"
fi
install -m 0600 "$tmp_config" "$CONFIG_PATH"

# The official package provides its own service definition. Do not replace it.
systemctl enable sing-box
systemctl restart sing-box
systemctl --no-pager --full is-active sing-box | grep -qx active || die "sing-box did not start; inspect: journalctl -u sing-box -e"

ufw allow "$PORT/tcp"

printf '\n===== CLIENT SETTINGS =====\n'
printf 'Server     : %s\n' "${SERVER_IP:-<server public IPv4>}"
printf 'Port       : %s\nUUID       : %s\nSNI        : %s\nPublicKey  : %s\nShortID    : %s\nFlow       : xtls-rprx-vision\n' \
  "$PORT" "$UUID" "$SNI" "$PUBLIC_KEY" "$SHORT_ID"
printf '\nVLESS URL:\n'
printf 'vless://%s@%s:%s?encryption=none&security=reality&flow=xtls-rprx-vision&sni=%s&pbk=%s&sid=%s#Reality\n' \
  "$UUID" "${SERVER_IP:-<server-public-ipv4>}" "$PORT" "$SNI" "$PUBLIC_KEY" "$SHORT_ID"
